Make Bond Issuance work on DABL
digital-asset/ex-bond-issuance pull request #163
Opened 2020-12-04 10:20 UTC by gaborh-da

2021-01-05 09:00 UTC, tamaskalcza-da requested changes

2021-01-05 09:00 UTC, tamaskalcza-da commented on src/main/daml/DA/RefApps/Bond/Test/MarketSetupScript.daml
> +setupMarketWithParties parties@BondIssuanceParties{..} = do
Wouldn't this be the same?
```suggestion
setupMarketWithParties parties = do
```

2021-01-05 09:00 UTC, tamaskalcza-da commented on triggers/src/main/daml/DA/RefApps/Bond/Triggers/TriggersLibrary.daml
> +main : [Daml.Trigger.Trigger ()]
Is this needed? If not, remove.

2021-01-05 09:00 UTC, tamaskalcza-da commented on ui-js/src/participants.json
> +{
Is this different from the other `participants.json`?

2021-01-05 09:52 UTC, gaborh-da commented on ui-js/src/participants.json
> +{
No, I think this is the same.
See the following part in the README:
https://github.com/digital-asset/ex-bond-issuance/pull/163/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R131

2021-01-05 09:56 UTC, gaborh-da commented on ui-js/src/participants.json
> +{
In the config, there is this part however:
https://github.com/digital-asset/ex-bond-issuance/pull/163/files#diff-403776bd79ad1c80b3e02fa443bf3fd9d3bdffa9315da03a967fe66041c798bcR7

So we need (unfortunately) the `participants.json` to be present in the ui dir "at UI compilation time".

I know this is not the best, but did not have an idea how to solve this.
Note that the file is only used in "non local dev mode".

I know that this is the same thing we discuss all the time how one needs to handle configuration in UI code but I still do not know the best solution for our case. We would need to investigate this and reshape all the refapps including this (but that is a different task, different PR).

2021-01-05 10:57 UTC, richardkapolnai-da commented on README.md
> +6. Run `make buildui`. Copy `participants.json` into `ui-js/src` with `cp participants.json ui-js/src/`. Run `npm run build` in `ui-js`. Then run `zip -r bondui.zip build/`. Upload `bondui.zip` to DA
Feel free to ignore: it's more elegant to expose this feature in the Makefile.
(A close example, but this part is unfinished: https://github.com/digital-asset/ex-supply-chain/blob/ERA-847-ui/Makefile)

2021-01-05 11:03 UTC, chrisnorris-da commented on src/main/daml/DA/RefApps/Bond/Test/MarketSetupScript.daml
> +setupMarketWithParties parties@BondIssuanceParties{..} = do
That would take operator out of scope .. so not the same.

2021-01-06 15:46 UTC, tamaskalcza-da approved these changes

2021-01-07 07:23 UTC, gaborh-da commented
I checked once again and it works with the merged master.

2021-01-07 07:23 UTC, merged